In [5]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([1, 2, 3, 4, 5,6,7])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798]
asin: [0.14334757 0.2897517  0.44291104 0.60824558 0.79560295 1.0296968
 1.57079633]
acos: [1.42744876 1.28104463 1.12788528 0.96255075 0.77519337 0.54109953
 0.        ]
atan: [0.78539816 1.10714872 1.24904577 1.32581766 1.37340077 1.40564765
 1.42889927]
exp: [   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591
  403.42879349 1096.63315843]
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015]
abs: [1 2 3 4 5 6 7]
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131]
rem: [1 0 1 0 1 0 1]
round: [1 2 3 4 5 6 7]
floor: [1. 2. 3. 4. 5. 6. 7.]
ceil: [1. 2. 3. 4. 5. 6. 7.]


In [6]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns
# Creating a 3x2 matrix
matrix = np.array([[1, 2], [3, 4],[4, 2]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)






Matrix:
 [[1 2]
 [3 4]
 [4 2]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.7568025   0.90929743]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]
 [-0.65364362 -0.41614684]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]
 [ 1.15782128 -2.18503986]]

asine:
 [[0.25268026 0.52359878]
 [0.84806208 1.57079633]
 [1.57079633 0.52359878]]

acosine:
 [[1.31811607 1.04719755]
 [0.72273425 0.        ]
 [0.         1.04719755]]

atangent:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]
 [1.32581766 1.10714872]]

exp:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]
 [54.59815003  7.3890561 ]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.38629436 0.69314718]]

abs:
 [[1 2]
 [3 4]
 [4 2]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.         1.41421356]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]
 [0 0]]

round:
 [[1 2]
 [3 4]
 [4 2]]

floor:
 [[1. 2.]
 [3. 4.]
 [4. 2.]]

ceil:
 [[1. 2.]
 [3

In [7]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns
# Creating a 2x3 matrix
matrix = np.array([[1.1,2.9,5.6], [3, 4, 9]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[1.1 2.9 5.6]
 [3.  4.  9. ]]

sin:
 [[ 0.89120736  0.23924933 -0.63126664]
 [ 0.14112001 -0.7568025   0.41211849]]

cos:
 [[ 0.45359612 -0.97095817  0.77556588]
 [-0.9899925  -0.65364362 -0.91113026]]

tan:
 [[ 1.96475966 -0.24640539 -0.81394328]
 [-0.14254654  1.15782128 -0.45231566]]

asine:
 [[0.12252858 0.32807598 0.67157818]
 [0.33983691 0.46055399 1.57079633]]

acosine:
 [[1.44826774 1.24272035 0.89921815]
 [1.23095942 1.11024234 0.        ]]

atangent:
 [[0.83298127 1.23873686 1.39408747]
 [1.24904577 1.32581766 1.46013911]]

exp:
 [[3.00416602e+00 1.81741454e+01 2.70426407e+02]
 [2.00855369e+01 5.45981500e+01 8.10308393e+03]]

log (natural):
 [[0.09531018 1.06471074 1.7227666 ]
 [1.09861229 1.38629436 2.19722458]]

abs:
 [[1.1 2.9 5.6]
 [3.  4.  9. ]]

sqrt:
 [[1.04880885 1.70293864 2.36643191]
 [1.73205081 2.         3.        ]]

rem (remainder when divided by 2):
 [[1.1 0.9 1.6]
 [1.  0.  1. ]]

round:
 [[1. 3. 6.]
 [3. 4. 9.]]

floor:
 [[1. 2. 5.]
 [3. 4. 9.]]

c